Update lab_prepare docker installation
systems-cs-pub-ro/uso-lab pull request #4
Opened 2022-11-04 07:09 UTC by edi33416

The previous script assumed that the arch was `amd64`.
This caused the setup to fail on `arm64` machines.

Replaced the steps with docker's script that does all the machinery in the back. [0]

Also, I added the current user to the `docker` group so the user won't be required to use `sudo` each time it interacts with docker.

[0] - https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/

2022-11-04 07:36 UTC, dandrei279 requested changes

2022-11-04 07:36 UTC, dandrei279 commented on labs/03-user/lab-container/lab_prepare.sh
> +    sudo apt-get upgrade
```suggestion
    sudo apt-get upgrade -y 
```

2022-11-04 07:36 UTC, dandrei279 commented on labs/03-user/lab-container/lab_prepare.sh
> +    curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
Missing docker-compose

2022-11-04 07:36 UTC, dandrei279 commented on labs/07-networking/lab-container/lab_prepare.sh
> +    sudo apt-get upgrade
```suggestion
    sudo apt-get upgrade -y
```

2022-11-04 07:36 UTC, dandrei279 commented on labs/07-networking/lab-container/lab_prepare.sh
> +    curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
Missing docker-compose

2022-11-04 07:36 UTC, dandrei279 commented on labs/09-task-admin/lab-container/lab_prepare.sh
> +    sudo apt-get upgrade
```suggestion
    sudo apt-get upgrade -y
```

2022-11-04 07:36 UTC, dandrei279 commented on labs/09-task-admin/lab-container/lab_prepare.sh
> +    curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
Missing docker-compose

2022-11-23 07:01 UTC, dandrei279 approved these changes

2024-10-30 22:21 UTC, Sergiu121 commented
Integrated in another branch.

2024-10-30 22:21 UTC, closed without merging